from: markdown
# reader: may be used instead of from:
to: latex
# writer: may be used instead of to:

# leave blank for output to stdout:
output-file: xsim-list-test.tex
# leave blank for input from stdin, use [] for no input:
input-file: xsim-list-test.md

standalone: true
self-contained: false

# Filters will be assumed to be Lua filters if they have
# the .lua extension, and json filters otherwise.  But
# the filter type can also be specified explicitly, as shown.
# Filters are run in the order specified.
# To include the built-in citeproc filter, use either `citeproc`
# or `{type: citeproc}`.
filters:
- xsim-list.lua
- chemformula.lua


pdf-engine: lualatex
pdf-engine-opts:
- "-shell-escape"
# you may also use pdf-engine-opt: with a single option
# pdf-engine-opt: "-shell-escape"